### ISSUE TITLE
Header creates white empty space on small screens

### ISSUE THREAD

**Issue by Karakaii** [empiricaly/meteor-empirica-core#252]
On small screen sizes the header (with the `New Player`, `About, and other buttons) does something weird and creates a big blank on the screen.  I tried this both with Chrome and Firefox. empirica:core 1.16.0.
![image](https://user-images.githubusercontent.com/60732953/119519262-313d7f00-bd71-11eb-8a7e-9dce3fc0e08f.png)

I believe the problem comes from the following styling that is set to this part of the header
``` css
.bp3-navbar-group .bp3-align-right {
  float: right;
}
```

Taking this part out fixes the problem.
![image (1)](https://user-images.githubusercontent.com/60732953/119519522-68ac2b80-bd71-11eb-91c2-843fccf36ef1.png)

Maybe replacing it with this sort of styling is best?
``` css
.bp3-navbar-group .bp3-align-right {
  float: none;
  display: flex;
  justify-content: right;
}
```
